module.exports = {
  ALL_RIGHT: 'ALL_RIGHT',

  VIEW_ACTIVITY: 'VIEW_ACTIVITY',
  CREATE_ACTIVITY: 'CREATE_ACTIVITY',
  EDIT_ACTIVITY: 'EDIT_ACTIVITY',
  REMOVE_ACTIVITY: 'REMOVE_ACTIVITY',

  VIEW_GROUP: 'VIEW_GROUP',
  EDIT_GROUP: 'EDIT_GROUP',
  CREATE_GROUP: 'CREATE_GROUP',
  SUBSCRIBE_GROUP: 'SUBSCRIBE_GROUP',
  UNSUBSCRIBE_GROUP: 'UNSUBSCRIBE_GROUP',
  REMOVE_GROUP: 'REMOVE_GROUP',

  VIEW_LESSON: 'VIEW_LESSON',
  VIEW_LESSON_STATISTIC: 'VIEW_LESSON_STATISTIC',
  EDIT_LESSON: 'EDIT_LESSON',
  CHECKIN_LESSON: 'CHECKIN_LESSON',
  CREATE_LESSON: 'CREATE_LESSON',

  VIEW_MESSAGE: 'VIEW_MESSAGE',
  EDIT_MESSAGE: 'EDIT_MESSAGE',
  CREATE_MESSAGE: 'CREATE_MESSAGE',
  REMOVE_MESSAGE: 'REMOVE_MESSAGE',
  READ_MESSAGE: 'READ_MESSAGE',

  CREATE_NOTE: 'CREATE_NOTE',
  VIEW_NOTE: 'VIEW_NOTE',
  EDIT_NOTE: 'EDIT_NOTE',
  REMOVE_NOTE: 'REMOVE_NOTE',

  CREATE_USER: 'CREATE_USER',
  EDIT_USER: 'EDIT_USER',
  REMOVE_USER: 'REMOVE_USER',
  EDIT_SETTING: 'EDIT_SETTING',

  VIEW_STATISTICS: 'VIEW_STATISTICS',
};
